server:
  servlet:
    context-path: /api
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    user: root
    password: root
    change-log: classpath:db/changelog/changelog.yml