server:
  servlet:
    context-path: /api
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    url: ${MIGRATIONS_DATABASE_URL}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    change-log: classpath:db/changelog/changelog.yml